Repository wecode-bootcamp-korea/47-1st-seoulminer-frontend, pull requests merged in 2023-06, with the labels that each got.

#4 [47기 이지원] Footer/layout 구현
  package-lock.json
  package.json
  src/Router.js
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
Labels: 완료

#1 [47기 양회진] product 미리보기 컴포넌트 구현
  .stylelintrc.js
  public/data/MainData.json
  src/Router.js
  src/essets/images/IMG_7631.jpg
  src/pages/Main.js
  src/pages/Product.js
  src/pages/Product.scss
  src/pages/Products.js
  src/pages/Products.scss
Labels: 완료

#6 [47기 이지원]ADD : footer-layout 상수데이터 추가
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Footer/FooterData.js
Labels: 멘토 리뷰 요청

#3 [47기 이지원] NavToggle.js 리팩토링 완료
  package-lock.json
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Nav/LoginButtons/LoginBtn.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/NavData.js
  src/components/Nav/NavToggle/NavToggle.js
  src/components/Nav/NavToggle/NavToggle.scss
  src/components/Nav/NavToggle/NavToggleData.js
  src/pages/Main.js
Labels: 멘토 리뷰 요청, 완료

#5 [47기 양회진]Login page 레이아웃 및 기능구현
  .stylelintrc.js
  src/Router.js
  src/components/Footer/Footer.scss
  src/components/SignInput.js
  src/pages/Login.js
  src/pages/Login.scss
Labels: 완료
